version: "3"

services:
  web:
    container_name: agate_container_nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web:/var/www/html  
      - ./conf.d:/etc/nginx/conf.d 
    
  php:
    container_name: agate_container_php
    build: php
    restart: always
    volumes:
      - ./web:/var/www/html

  database:
    container_name: agate_container_database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mdp_atip
      POSTGRES_USER: atip
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    container_name: agate_container_adminer
    image: adminer
    restart: always
    ports: 
      - 8080:8080

    

